apiVersion: v1
kind: Namespace
metadata:
  name: capi-operator-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capi-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: capo-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cabpt-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: cacppt-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: orc-system
