apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: adguard
spec:
  interval: 1h
  chart:
    spec:
      chart: adguard-home
      sourceRef:
        kind: HelmRepository
        name: gabe565
  values:
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 512Mi
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 2Gi
    service:
      dns-tcp:
        annotations:
          metallb.universe.tf/allow-shared-ip: null
          lbipam.cilium.io/ips: "192.168.25.100"
          lbipam.cilium.io/sharing-key: "adguard-home"
      dns-udp:
        annotations:
          metallb.universe.tf/allow-shared-ip: null
          lbipam.cilium.io/ips: "192.168.25.100"
          lbipam.cilium.io/sharing-key: "adguard-home"
